version: '3.8'

services:
  backend:
    build: ./backend
    env_file:
      - .env
    command: sh -c "pip install --no-cache-dir python-multipart==0.0.9 && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    volumes:
      # Ánh xạ thư mục backend ở máy bạn vào trong Docker
      # Nhờ dòng này, file uit_chatbot.db sẽ được lưu vĩnh viễn ở máy bạn, không bị mất!
        - ./backend:/app
        - ./rag_app:/app/rag_app
        - ./data:/app/data
        - ./storage:/app/storage
        - ./scripts:/app/scripts
    environment:
      - CHOKIDAR_USEPOLLING=true

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules # Dòng này cực kỳ quan trọng để Docker tự quản lý thư viện riêng
    depends_on:
      - backend
